// lang-en.js
export const translations = {
    // --- New Strings ---
    bootStatus: "Initializing Interface...",
    deviceProfile: "Device Profile",
    deviceCalibration: "Device Calibration",
    diagnosticIntro: "Press \"START\" for system analysis.",
    commandHistoryLog: "Command History Log",
    noCommandsYet: "No commands executed in this session.",
    ramLabel: "🧠 RAM",

    // --- Existing Strings ---
    aiGreeting: ["System analysis complete. TTP-AI online and ready to optimize performance.","Welcome back! I've been processing data to better serve your device.","Greetings! My algorithms are primed. Let's unlock your device's full potential."],
    comingSoon: "Coming Soon",
    aiCommandLog: "AI Diagnostic Center",
    diagnosticIntro: "Press \"Start Diagnostics\" for the AI to analyze and provide optimal recommendations for your system.",
    diagnosticStart: "Start Diagnostics",
    diagnosticRunning: "Analyzing...",
    diagnosticRerun: "Rerun Diagnostics",
    diagResultTempHigh: "Diagnostics complete: System temperature is high",
    diagResultBatteryLow: "Diagnostics complete: Energy levels are critical",
    diagResultTempWarm: "Diagnostics complete: Temperature is elevated",
    diagResultAllGood: "Diagnostics complete: All parameters are optimal.",
    diagActionBoost: "Activate Performance Boost",
    diagActionConserve: "Activate Power Conservation",
    diagActionLag: "Reduce Lag & Optimize Thermals",
    diagReason: "Primary cause",

    loadingDeviceInfo: "🔄 Analyzing device parameters...",
    errorDeviceInfo: "Error interfacing with device hardware.",
    errorUpdateKey: "Error loading Key info.",
    errorUpdateDevice: "Error loading Device info.",
    errorUpdateStats: "Error loading system stats.",
    keyLabel: "Auth Key",
    expiryLabel: "Valid Until",
    deviceNameLabel: "📱 Designation",
    modelLabel: "📦 Unit Model",
    androidLabel: "🛠️ OS Version",
    socLabel: "⚙️ Processor Unit",
    gpuLabel: "🎮 Graphics Core",
    liveSystemStats: "📊 Real-time System Telemetry",
    batteryLevel: "Energy Level",
    batteryTemp: "Core Temperature",
    cpuCurrentFreq: "CPU Core Activity",
    cpuCore: "Core",
    serverEffective: "🎮 Global Optimization Matrix | Server",
    recoveryEffective: "🔧 System Restore Protocols | Server",
    deviceOptimization: "🧠 On-Device Heuristics",
    reduceLag: "Lag Reduction",
    boostPerformance: "Performance Boost",
    smoothSystem: "System Fluidity",
    betterMultitasking: "Multitasking Enh.",
    mediumTouch: "Touch Input (Med)",
    highTouch: "Touch Input (High)",
    decreaseDPI: "DPI Scaling (-)",
    increaseDPI: "DPI Scaling (+)",
    increaseDPIUltra: "DPI Scaling (++)",
    cuongche: "Forced Ram",
    fps90: "90FPS",
    fps120: "120FPS",
    gamenhetam: "Fine tune DPI slightly center FOV far",
    gameboc: "Fine-tune DPI pioneering near FOV",
    restoreTouch: "Restore Touch Calib.",
    restoreDPI: "Restore DPI Defaults",
    restoreRAM: "Restore Memory Config",
    restoreAll: "System Normalization",
    rebootDevice: "System Reboot",
    toast_pending_label: "TRANSMITTING",
    toast_pending: "Command sent to neural network...",
    toast_success: "✅ Command Executed",
    toast_error: "⚠️ Anomaly Detected",
    toast_completed: "Process completed successfully.",
    aiConsciousnessScanTitle: "AI CONSCIOUSNESS SCAN",
    aiConsciousnessScanMessage: "Consciousness stream active... observing user patterns.",
    neuralLinkActive: "NEURAL LINK ACTIVE...",
    rainWords: ["ANALYZING", "OBSERVING", "CONNECTING", "THINKING", "ONLINE", "LOGGING", "USER_DETECTED"],
};