// lang-vi.js
export const translations = {
    // --- New Strings ---
    bootStatus: "Đang khởi tạo giao diện...",
    deviceProfile: "Hồ sơ thiết bị",
    deviceCalibration: "Hiệu chỉnh thiết bị",
    diagnosticIntro: "Nhấn \"START\" để phân tích hệ thống.",
    commandHistoryLog: "Nhật Ký Lệnh",
    noCommandsYet: "Chưa có lệnh nào được thực thi.",
    ramLabel: "🧠 RAM",

    // --- Existing Strings ---
    aiGreeting: ["Phân tích hệ thống hoàn tất. TTP-AI đã trực tuyến và sẵn sàng tối ưu hiệu năng.","Chào mừng trở lại! Tôi đã xử lý dữ liệu để phục vụ thiết bị của bạn tốt hơn.","Kính chào! Các thuật toán của tôi đã sẵn sàng. Hãy khai phá toàn bộ tiềm năng thiết bị của bạn."],
    comingSoon: "Sắp ra mắt",

    aiCommandLog: "Trung tâm Chẩn đoán AI",
    diagnosticIntro: "Nhấn \"Bắt đầu Chẩn đoán\" để AI phân tích và đưa ra đề xuất tối ưu cho hệ thống của bạn.",
    diagnosticStart: "Bắt đầu Chẩn đoán",
    diagnosticRunning: "Đang phân tích...",
    diagnosticRerun: "Chẩn đoán lại",
    diagResultTempHigh: "Chẩn đoán hoàn tất: Nhiệt độ hệ thống cao",
    diagResultBatteryLow: "Chẩn đoán hoàn tất: Mức năng lượng tới hạn",
    diagResultTempWarm: "Chẩn đoán hoàn tất: Nhiệt độ có dấu hiệu tăng",
    diagResultAllGood: "Chẩn đoán hoàn tất: Mọi thông số đều tối ưu.",
    diagActionBoost: "Kích hoạt Tăng cường Hiệu suất",
    diagActionConserve: "Kích hoạt Tiết kiệm Năng lượng",
    diagActionLag: "Giảm Giật Lag & Tối ưu nhiệt",
    diagReason: "Nguyên nhân chính",

    loadingDeviceInfo: "🔄 Đang phân tích thông số thiết bị...",
    errorDeviceInfo: "Lỗi giao tiếp với phần cứng thiết bị.",
    errorUpdateKey: "Lỗi tải thông tin Key.",
    errorUpdateDevice: "Lỗi tải thông tin thiết bị.",
    errorUpdateStats: "Lỗi tải dữ liệu hệ thống.",
    keyLabel: "Key Xác Thực",
    expiryLabel: "Hiệu Lực Đến",
    deviceNameLabel: "📱 Định Danh",
    modelLabel: "📦 Model Thiết Bị",
    androidLabel: "🛠️ Phiên Bản OS",
    socLabel: "⚙️ Bộ Vi Xử Lý",
    gpuLabel: "🎮 Lõi Đồ Họa",
    liveSystemStats: "📊 Dữ Liệu Hệ Thống Thời Gian Thực",
    batteryLevel: "Mức Năng Lượng",
    batteryTemp: "Nhiệt Độ Lõi",
    cpuCurrentFreq: "Hoạt Động Lõi CPU",
    cpuCore: "Lõi",
    serverEffective: "🎮 Tối Ưu Toàn Cục",
    recoveryEffective: "🔧 Giao Thức Khôi Phục Hệ Thống",
    deviceOptimization: "🧠 Phân Tích Heuristic Trên Thiết Bị",
    reduceLag: "Giảm Giật Lag",
    boostPerformance: "Tăng Cường Hiệu Suất",
    smoothSystem: "Độ Mượt Hệ Thống",
    betterMultitasking: "Cải Thiện Đa Nhiệm",
    mediumTouch: "Độ Nhạy Cảm Ứng (TB)",
    highTouch: "Độ Nhạy Cảm Ứng (Cao)",
    decreaseDPI: "Tinh Chỉnh DPI (-)",
    increaseDPI: "Tinh Chỉnh DPI (+)",
    increaseDPIUltra: "Tinh Chỉnh DPI (++)",
    cuongche: "Cưỡng Chế Ram ( Vip )",
    fps90: "90FPS",
    fps120: "120FPS",
    gamenhetam: "Tinh chỉnh DPI nhẹ tâm FOV xa",
    gameboc: "Tinh chỉnh DPI tiên phong FOV gần",
    restoreTouch: "Khôi Phục Cảm Ứng",
    restoreDPI: "Khôi Phục DPI Gốc",
    restoreRAM: "Khôi Phục RAM Gốc",
    restoreAll: "Chuẩn Hóa Hệ Thống",
    rebootDevice: "Khởi Động Lại Hệ Thống",
    toast_pending_label: "ĐANG TRUYỀN LỆNH",
    toast_pending: "Đang gửi lệnh tới mạng neural...",
    toast_success: "✅ Lệnh Đã Thực Thi",
    toast_error: "⚠️ Phát Hiện Bất Thường",
    toast_completed: "Quá trình hoàn tất thành công.",
    aiConsciousnessScanTitle: "QUÉT Ý THỨC AI",
    aiConsciousnessScanMessage: "Luồng ý thức đang hoạt động... quan sát hành vi người dùng.",
    neuralLinkActive: "KẾT NỐI THẦN KINH...",
    rainWords: ["PHÂN_TÍCH", "QUAN_SÁT", "KẾT_NỐI", "SUY_NGHĨ", "TRỰC_TUYẾN", "GHI_NHẬN", "NGƯỜI_DÙNG"],
};